// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assembly_machines.sql

package database

import (
	"context"
	"database/sql"
)

const addAssemblyMachine = `-- name: AddAssemblyMachine :one
INSERT INTO assembly_machines(
  entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe
`

type AddAssemblyMachineParams struct {
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
}

func (q *Queries) AddAssemblyMachine(ctx context.Context, arg AddAssemblyMachineParams) (AssemblyMachine, error) {
	row := q.db.QueryRowContext(ctx, addAssemblyMachine,
		arg.EntityID,
		arg.CraftingCategories,
		arg.CraftingSpeed,
		arg.EnergySource,
		arg.EnergyUsage,
		arg.FixedRecipe,
	)
	var i AssemblyMachine
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CraftingCategories,
		&i.CraftingSpeed,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.FixedRecipe,
	)
	return i, err
}

const getAllAssemblyMachineValues = `-- name: GetAllAssemblyMachineValues :many
SELECT id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe FROM assembly_machines
`

func (q *Queries) GetAllAssemblyMachineValues(ctx context.Context) ([]AssemblyMachine, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssemblyMachineValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssemblyMachine
	for rows.Next() {
		var i AssemblyMachine
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.CraftingCategories,
			&i.CraftingSpeed,
			&i.EnergySource,
			&i.EnergyUsage,
			&i.FixedRecipe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAssemblyMachines = `-- name: GetAllAssemblyMachines :many
SELECT assembly_machines.id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe, entities.id, name, prototype_type, entity_order, localised_name
FROM assembly_machines
LEFT JOIN entities
ON assembly_machines.entity_id = entities.id
`

type GetAllAssemblyMachinesRow struct {
	ID                 int64
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAllAssemblyMachines(ctx context.Context) ([]GetAllAssemblyMachinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAssemblyMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAssemblyMachinesRow
	for rows.Next() {
		var i GetAllAssemblyMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.CraftingCategories,
			&i.CraftingSpeed,
			&i.EnergySource,
			&i.EnergyUsage,
			&i.FixedRecipe,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssemblyMachineByAssemblyMachineID = `-- name: GetAssemblyMachineByAssemblyMachineID :one
SELECT assembly_machines.id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe, entities.id, name, prototype_type, entity_order, localised_name
FROM assembly_machines
LEFT JOIN entities
ON assembly_machines.entity_id = entities.id
WHERE assembly_machines.id = ?1
`

type GetAssemblyMachineByAssemblyMachineIDRow struct {
	ID                 int64
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAssemblyMachineByAssemblyMachineID(ctx context.Context, id int64) (GetAssemblyMachineByAssemblyMachineIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssemblyMachineByAssemblyMachineID, id)
	var i GetAssemblyMachineByAssemblyMachineIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CraftingCategories,
		&i.CraftingSpeed,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.FixedRecipe,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getAssemblyMachineByEntityID = `-- name: GetAssemblyMachineByEntityID :one
SELECT assembly_machines.id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe, entities.id, name, prototype_type, entity_order, localised_name
FROM assembly_machines
LEFT JOIN entities
ON assembly_machines.entity_id = entities.id
WHERE entities.id = ?1
`

type GetAssemblyMachineByEntityIDRow struct {
	ID                 int64
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAssemblyMachineByEntityID(ctx context.Context, id int64) (GetAssemblyMachineByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssemblyMachineByEntityID, id)
	var i GetAssemblyMachineByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CraftingCategories,
		&i.CraftingSpeed,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.FixedRecipe,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getAssemblyMachineByName = `-- name: GetAssemblyMachineByName :one
SELECT assembly_machines.id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe, entities.id, name, prototype_type, entity_order, localised_name
FROM assembly_machines
LEFT JOIN entities
ON assembly_machines.entity_id = entities.id
WHERE entities.name = ?1
`

type GetAssemblyMachineByNameRow struct {
	ID                 int64
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAssemblyMachineByName(ctx context.Context, name string) (GetAssemblyMachineByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getAssemblyMachineByName, name)
	var i GetAssemblyMachineByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CraftingCategories,
		&i.CraftingSpeed,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.FixedRecipe,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateAssemblyMachineByID = `-- name: UpdateAssemblyMachineByID :one
UPDATE assembly_machines
SET entity_id = ?1,
crafting_categories = ?2,
crafting_speed = ?3,
energy_source = ?4,
energy_usage = ?5,
fixed_recipe = ?6
WHERE id = ?7
RETURNING id, entity_id, crafting_categories, crafting_speed, energy_source, energy_usage, fixed_recipe
`

type UpdateAssemblyMachineByIDParams struct {
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
	ID                 int64
}

func (q *Queries) UpdateAssemblyMachineByID(ctx context.Context, arg UpdateAssemblyMachineByIDParams) (AssemblyMachine, error) {
	row := q.db.QueryRowContext(ctx, updateAssemblyMachineByID,
		arg.EntityID,
		arg.CraftingCategories,
		arg.CraftingSpeed,
		arg.EnergySource,
		arg.EnergyUsage,
		arg.FixedRecipe,
		arg.ID,
	)
	var i AssemblyMachine
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CraftingCategories,
		&i.CraftingSpeed,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.FixedRecipe,
	)
	return i, err
}
