// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boilers.sql

package database

import (
	"context"
	"database/sql"
)

const addBoiler = `-- name: AddBoiler :one
INSERT INTO boilers(
  entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid
`

type AddBoilerParams struct {
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
}

func (q *Queries) AddBoiler(ctx context.Context, arg AddBoilerParams) (Boiler, error) {
	row := q.db.QueryRowContext(ctx, addBoiler,
		arg.EntityID,
		arg.EnergySource,
		arg.EnergyConsumption,
		arg.TargetTemperature,
		arg.Mode,
		arg.InputFluid,
		arg.OutputFluid,
	)
	var i Boiler
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.EnergyConsumption,
		&i.TargetTemperature,
		&i.Mode,
		&i.InputFluid,
		&i.OutputFluid,
	)
	return i, err
}

const getAllBoilerValues = `-- name: GetAllBoilerValues :many
SELECT id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid FROM boilers
`

func (q *Queries) GetAllBoilerValues(ctx context.Context) ([]Boiler, error) {
	rows, err := q.db.QueryContext(ctx, getAllBoilerValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Boiler
	for rows.Next() {
		var i Boiler
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergySource,
			&i.EnergyConsumption,
			&i.TargetTemperature,
			&i.Mode,
			&i.InputFluid,
			&i.OutputFluid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBoilers = `-- name: GetAllBoilers :many
SELECT boilers.id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM boilers
LEFT JOIN entities
ON boilers.entity_id = entities.id
`

type GetAllBoilersRow struct {
	ID                int64
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
	ID_2              sql.NullInt64
	Name              sql.NullString
	PrototypeType     sql.NullString
	EntityOrder       sql.NullString
	LocalisedName     sql.NullString
}

func (q *Queries) GetAllBoilers(ctx context.Context) ([]GetAllBoilersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBoilers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBoilersRow
	for rows.Next() {
		var i GetAllBoilersRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergySource,
			&i.EnergyConsumption,
			&i.TargetTemperature,
			&i.Mode,
			&i.InputFluid,
			&i.OutputFluid,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoilerByBoilerID = `-- name: GetBoilerByBoilerID :one
SELECT boilers.id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM boilers
LEFT JOIN entities
ON boilers.entity_id = entities.id
WHERE boilers.id = ?1
`

type GetBoilerByBoilerIDRow struct {
	ID                int64
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
	ID_2              sql.NullInt64
	Name              sql.NullString
	PrototypeType     sql.NullString
	EntityOrder       sql.NullString
	LocalisedName     sql.NullString
}

func (q *Queries) GetBoilerByBoilerID(ctx context.Context, id int64) (GetBoilerByBoilerIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBoilerByBoilerID, id)
	var i GetBoilerByBoilerIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.EnergyConsumption,
		&i.TargetTemperature,
		&i.Mode,
		&i.InputFluid,
		&i.OutputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getBoilerByEntityID = `-- name: GetBoilerByEntityID :one
SELECT boilers.id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM boilers
LEFT JOIN entities
ON boilers.entity_id = entities.id
WHERE entities.id = ?1
`

type GetBoilerByEntityIDRow struct {
	ID                int64
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
	ID_2              sql.NullInt64
	Name              sql.NullString
	PrototypeType     sql.NullString
	EntityOrder       sql.NullString
	LocalisedName     sql.NullString
}

func (q *Queries) GetBoilerByEntityID(ctx context.Context, id int64) (GetBoilerByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBoilerByEntityID, id)
	var i GetBoilerByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.EnergyConsumption,
		&i.TargetTemperature,
		&i.Mode,
		&i.InputFluid,
		&i.OutputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getBoilerByName = `-- name: GetBoilerByName :one
SELECT boilers.id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM boilers
LEFT JOIN entities
ON boilers.entity_id = entities.id
WHERE entities.name = ?1
`

type GetBoilerByNameRow struct {
	ID                int64
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
	ID_2              sql.NullInt64
	Name              sql.NullString
	PrototypeType     sql.NullString
	EntityOrder       sql.NullString
	LocalisedName     sql.NullString
}

func (q *Queries) GetBoilerByName(ctx context.Context, name string) (GetBoilerByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getBoilerByName, name)
	var i GetBoilerByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.EnergyConsumption,
		&i.TargetTemperature,
		&i.Mode,
		&i.InputFluid,
		&i.OutputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateBoilerByID = `-- name: UpdateBoilerByID :one
UPDATE boilers
SET entity_id = ?1,
energy_source = ?2,
energy_consumption = ?3,
target_temperature = ?4,
mode = ?5,
input_fluid = ?6,
output_fluid = ?7
WHERE id = ?8
RETURNING id, entity_id, energy_source, energy_consumption, target_temperature, mode, input_fluid, output_fluid
`

type UpdateBoilerByIDParams struct {
	EntityID          int64
	EnergySource      []byte
	EnergyConsumption sql.NullFloat64
	TargetTemperature sql.NullFloat64
	Mode              sql.NullString
	InputFluid        sql.NullInt64
	OutputFluid       sql.NullInt64
	ID                int64
}

func (q *Queries) UpdateBoilerByID(ctx context.Context, arg UpdateBoilerByIDParams) (Boiler, error) {
	row := q.db.QueryRowContext(ctx, updateBoilerByID,
		arg.EntityID,
		arg.EnergySource,
		arg.EnergyConsumption,
		arg.TargetTemperature,
		arg.Mode,
		arg.InputFluid,
		arg.OutputFluid,
		arg.ID,
	)
	var i Boiler
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.EnergyConsumption,
		&i.TargetTemperature,
		&i.Mode,
		&i.InputFluid,
		&i.OutputFluid,
	)
	return i, err
}
