// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package database

import (
	"context"
	"database/sql"
)

const addEntity = `-- name: AddEntity :one
INSERT INTO entities(
  name, prototype_type, entity_order, localised_name
) VALUES (
  ?1, ?2, ?3, ?4
) RETURNING id, name, prototype_type, entity_order, localised_name
`

type AddEntityParams struct {
	Name          string
	PrototypeType string
	EntityOrder   sql.NullString
	LocalisedName string
}

func (q *Queries) AddEntity(ctx context.Context, arg AddEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, addEntity,
		arg.Name,
		arg.PrototypeType,
		arg.EntityOrder,
		arg.LocalisedName,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const deleteEntityByID = `-- name: DeleteEntityByID :exec
DELETE FROM entities WHERE id = ?1
`

func (q *Queries) DeleteEntityByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntityByID, id)
	return err
}

const deleteEntityByName = `-- name: DeleteEntityByName :exec
DELETE FROM entities WHERE name = ?1 AND prototype_type = ?2
`

type DeleteEntityByNameParams struct {
	Name          string
	PrototypeType string
}

func (q *Queries) DeleteEntityByName(ctx context.Context, arg DeleteEntityByNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntityByName, arg.Name, arg.PrototypeType)
	return err
}

const getAllEntities = `-- name: GetAllEntities :many
SELECT id, name, prototype_type, entity_order, localised_name FROM entities
`

func (q *Queries) GetAllEntities(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesByName = `-- name: GetEntitiesByName :many
SELECT id, name, prototype_type, entity_order, localised_name FROM entities WHERE name = ?1
`

func (q *Queries) GetEntitiesByName(ctx context.Context, name string) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, getEntitiesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, name, prototype_type, entity_order, localised_name FROM entities WHERE id = ?1
`

func (q *Queries) GetEntityByID(ctx context.Context, id int64) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getEntityByName = `-- name: GetEntityByName :one
SELECT id, name, prototype_type, entity_order, localised_name FROM entities WHERE name = ?1 AND prototype_type = ?2
`

type GetEntityByNameParams struct {
	Name          string
	PrototypeType string
}

func (q *Queries) GetEntityByName(ctx context.Context, arg GetEntityByNameParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntityByName, arg.Name, arg.PrototypeType)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateEntityLocalisedNameByID = `-- name: UpdateEntityLocalisedNameByID :one
UPDATE entities SET localised_name = ?1 WHERE id = ?2 RETURNING id, name, prototype_type, entity_order, localised_name
`

type UpdateEntityLocalisedNameByIDParams struct {
	LocalisedName string
	ID            int64
}

func (q *Queries) UpdateEntityLocalisedNameByID(ctx context.Context, arg UpdateEntityLocalisedNameByIDParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntityLocalisedNameByID, arg.LocalisedName, arg.ID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateEntityOrderByID = `-- name: UpdateEntityOrderByID :one
UPDATE entities SET entity_order = ?1 WHERE id = ?2 RETURNING id, name, prototype_type, entity_order, localised_name
`

type UpdateEntityOrderByIDParams struct {
	Order sql.NullString
	ID    int64
}

func (q *Queries) UpdateEntityOrderByID(ctx context.Context, arg UpdateEntityOrderByIDParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntityOrderByID, arg.Order, arg.ID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateEntityOrderByName = `-- name: UpdateEntityOrderByName :one
UPDATE entities SET entity_order = ?1 WHERE name = ?2 AND prototype_type = ?3 RETURNING id, name, prototype_type, entity_order, localised_name
`

type UpdateEntityOrderByNameParams struct {
	Order         sql.NullString
	Name          string
	PrototypeType string
}

func (q *Queries) UpdateEntityOrderByName(ctx context.Context, arg UpdateEntityOrderByNameParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntityOrderByName, arg.Order, arg.Name, arg.PrototypeType)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}
