// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package database

import (
	"context"
	"database/sql"
)

const addEntity = `-- name: AddEntity :one

INSERT INTO entities(
  name, entity_order
) VALUES (
  ?1, ?2
) RETURNING id, name, entity_order
`

type AddEntityParams struct {
	Name        string
	EntityOrder sql.NullString
}

func (q *Queries) AddEntity(ctx context.Context, arg AddEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, addEntity, arg.Name, arg.EntityOrder)
	var i Entity
	err := row.Scan(&i.ID, &i.Name, &i.EntityOrder)
	return i, err
}

const deleteEntityByID = `-- name: DeleteEntityByID :exec
DELETE FROM entities WHERE id = ?1
`

func (q *Queries) DeleteEntityByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntityByID, id)
	return err
}

const deleteEntityByName = `-- name: DeleteEntityByName :exec
DELETE FROM entities WHERE name = ?1
`

func (q *Queries) DeleteEntityByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteEntityByName, name)
	return err
}

const getAllEntities = `-- name: GetAllEntities :many

SELECT id, name, entity_order FROM entities
`

func (q *Queries) GetAllEntities(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(&i.ID, &i.Name, &i.EntityOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, name, entity_order FROM entities WHERE id = ?1
`

func (q *Queries) GetEntityByID(ctx context.Context, id int64) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(&i.ID, &i.Name, &i.EntityOrder)
	return i, err
}

const getEntityByName = `-- name: GetEntityByName :one
SELECT id, name, entity_order FROM entities WHERE name = ?1
`

func (q *Queries) GetEntityByName(ctx context.Context, name string) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntityByName, name)
	var i Entity
	err := row.Scan(&i.ID, &i.Name, &i.EntityOrder)
	return i, err
}

const updateEntityOrderByID = `-- name: UpdateEntityOrderByID :one
UPDATE entities SET entity_order = ?1 WHERE id = ?2 RETURNING id, name, entity_order
`

type UpdateEntityOrderByIDParams struct {
	Order sql.NullString
	ID    int64
}

func (q *Queries) UpdateEntityOrderByID(ctx context.Context, arg UpdateEntityOrderByIDParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntityOrderByID, arg.Order, arg.ID)
	var i Entity
	err := row.Scan(&i.ID, &i.Name, &i.EntityOrder)
	return i, err
}

const updateEntityOrderByName = `-- name: UpdateEntityOrderByName :one
UPDATE entities SET entity_order = ?1 WHERE name = ?2 RETURNING id, name, entity_order
`

type UpdateEntityOrderByNameParams struct {
	Order sql.NullString
	Name  string
}

func (q *Queries) UpdateEntityOrderByName(ctx context.Context, arg UpdateEntityOrderByNameParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntityOrderByName, arg.Order, arg.Name)
	var i Entity
	err := row.Scan(&i.ID, &i.Name, &i.EntityOrder)
	return i, err
}
