// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fluids.sql

package database

import (
	"context"
	"database/sql"
)

const addFluid = `-- name: AddFluid :one
INSERT INTO fluids(
  entity_id, fuel_value, gas_temperature, default_temperature, max_temperature
) VALUES (
  ?1, ?2, ?3, ?4, ?5
) RETURNING id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature
`

type AddFluidParams struct {
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
}

func (q *Queries) AddFluid(ctx context.Context, arg AddFluidParams) (Fluid, error) {
	row := q.db.QueryRowContext(ctx, addFluid,
		arg.EntityID,
		arg.FuelValue,
		arg.GasTemperature,
		arg.DefaultTemperature,
		arg.MaxTemperature,
	)
	var i Fluid
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FuelValue,
		&i.GasTemperature,
		&i.DefaultTemperature,
		&i.MaxTemperature,
	)
	return i, err
}

const getAllFluidValues = `-- name: GetAllFluidValues :many
SELECT id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature FROM fluids
`

func (q *Queries) GetAllFluidValues(ctx context.Context) ([]Fluid, error) {
	rows, err := q.db.QueryContext(ctx, getAllFluidValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fluid
	for rows.Next() {
		var i Fluid
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.FuelValue,
			&i.GasTemperature,
			&i.DefaultTemperature,
			&i.MaxTemperature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFluids = `-- name: GetAllFluids :many
SELECT fluids.id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature, entities.id, name, prototype_type, entity_order
FROM fluids
LEFT JOIN entities
ON fluids.entity_id = entities.id
`

type GetAllFluidsRow struct {
	ID                 int64
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
}

func (q *Queries) GetAllFluids(ctx context.Context) ([]GetAllFluidsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFluids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFluidsRow
	for rows.Next() {
		var i GetAllFluidsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.FuelValue,
			&i.GasTemperature,
			&i.DefaultTemperature,
			&i.MaxTemperature,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFluidByEntityID = `-- name: GetFluidByEntityID :one
SELECT fluids.id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature, entities.id, name, prototype_type, entity_order
FROM fluids
LEFT JOIN entities
ON fluids.entity_id = entities.id
WHERE entities.id = ?1
`

type GetFluidByEntityIDRow struct {
	ID                 int64
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
}

func (q *Queries) GetFluidByEntityID(ctx context.Context, id int64) (GetFluidByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFluidByEntityID, id)
	var i GetFluidByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FuelValue,
		&i.GasTemperature,
		&i.DefaultTemperature,
		&i.MaxTemperature,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const getFluidByFluidID = `-- name: GetFluidByFluidID :one
SELECT fluids.id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature, entities.id, name, prototype_type, entity_order
FROM fluids
LEFT JOIN entities
ON fluids.entity_id = entities.id
WHERE fluids.id = ?1
`

type GetFluidByFluidIDRow struct {
	ID                 int64
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
}

func (q *Queries) GetFluidByFluidID(ctx context.Context, id int64) (GetFluidByFluidIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFluidByFluidID, id)
	var i GetFluidByFluidIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FuelValue,
		&i.GasTemperature,
		&i.DefaultTemperature,
		&i.MaxTemperature,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const getFluidByName = `-- name: GetFluidByName :one
SELECT fluids.id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature, entities.id, name, prototype_type, entity_order
FROM fluids
LEFT JOIN entities
ON fluids.entity_id = entities.id
WHERE entities.name = ?1
`

type GetFluidByNameRow struct {
	ID                 int64
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
}

func (q *Queries) GetFluidByName(ctx context.Context, name string) (GetFluidByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getFluidByName, name)
	var i GetFluidByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FuelValue,
		&i.GasTemperature,
		&i.DefaultTemperature,
		&i.MaxTemperature,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const updateFluidByID = `-- name: UpdateFluidByID :one
UPDATE fluids
SET entity_id = ?1,
fuel_value = ?2,
gas_temperature = ?3,
default_temperature = ?4,
max_temperature = ?5
WHERE id = ?6
RETURNING id, entity_id, fuel_value, gas_temperature, default_temperature, max_temperature
`

type UpdateFluidByIDParams struct {
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
	ID                 int64
}

func (q *Queries) UpdateFluidByID(ctx context.Context, arg UpdateFluidByIDParams) (Fluid, error) {
	row := q.db.QueryRowContext(ctx, updateFluidByID,
		arg.EntityID,
		arg.FuelValue,
		arg.GasTemperature,
		arg.DefaultTemperature,
		arg.MaxTemperature,
		arg.ID,
	)
	var i Fluid
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FuelValue,
		&i.GasTemperature,
		&i.DefaultTemperature,
		&i.MaxTemperature,
	)
	return i, err
}
