// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generators.sql

package database

import (
	"context"
	"database/sql"
)

const addGenerator = `-- name: AddGenerator :one
INSERT INTO generators(
  entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid
`

type AddGeneratorParams struct {
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
}

func (q *Queries) AddGenerator(ctx context.Context, arg AddGeneratorParams) (Generator, error) {
	row := q.db.QueryRowContext(ctx, addGenerator,
		arg.EntityID,
		arg.EnergySource,
		arg.Effectivity,
		arg.FluidUsagePerTick,
		arg.MaximumTemperature,
		arg.BurnsFluid,
		arg.InputFluid,
	)
	var i Generator
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.Effectivity,
		&i.FluidUsagePerTick,
		&i.MaximumTemperature,
		&i.BurnsFluid,
		&i.InputFluid,
	)
	return i, err
}

const getAllGeneratorValues = `-- name: GetAllGeneratorValues :many
SELECT id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid FROM generators
`

func (q *Queries) GetAllGeneratorValues(ctx context.Context) ([]Generator, error) {
	rows, err := q.db.QueryContext(ctx, getAllGeneratorValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Generator
	for rows.Next() {
		var i Generator
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergySource,
			&i.Effectivity,
			&i.FluidUsagePerTick,
			&i.MaximumTemperature,
			&i.BurnsFluid,
			&i.InputFluid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGenerators = `-- name: GetAllGenerators :many
SELECT generators.id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM generators
LEFT JOIN entities
ON generators.entity_id = entities.id
`

type GetAllGeneratorsRow struct {
	ID                 int64
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAllGenerators(ctx context.Context) ([]GetAllGeneratorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGenerators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGeneratorsRow
	for rows.Next() {
		var i GetAllGeneratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergySource,
			&i.Effectivity,
			&i.FluidUsagePerTick,
			&i.MaximumTemperature,
			&i.BurnsFluid,
			&i.InputFluid,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeneratorByEntityID = `-- name: GetGeneratorByEntityID :one
SELECT generators.id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM generators
LEFT JOIN entities
ON generators.entity_id = entities.id
WHERE entities.id = ?1
`

type GetGeneratorByEntityIDRow struct {
	ID                 int64
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetGeneratorByEntityID(ctx context.Context, id int64) (GetGeneratorByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGeneratorByEntityID, id)
	var i GetGeneratorByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.Effectivity,
		&i.FluidUsagePerTick,
		&i.MaximumTemperature,
		&i.BurnsFluid,
		&i.InputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getGeneratorByGeneratorID = `-- name: GetGeneratorByGeneratorID :one
SELECT generators.id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM generators
LEFT JOIN entities
ON generators.entity_id = entities.id
WHERE generators.id = ?1
`

type GetGeneratorByGeneratorIDRow struct {
	ID                 int64
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetGeneratorByGeneratorID(ctx context.Context, id int64) (GetGeneratorByGeneratorIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGeneratorByGeneratorID, id)
	var i GetGeneratorByGeneratorIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.Effectivity,
		&i.FluidUsagePerTick,
		&i.MaximumTemperature,
		&i.BurnsFluid,
		&i.InputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getGeneratorByName = `-- name: GetGeneratorByName :one
SELECT generators.id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid, entities.id, name, prototype_type, entity_order, localised_name
FROM generators
LEFT JOIN entities
ON generators.entity_id = entities.id
WHERE entities.name = ?1
`

type GetGeneratorByNameRow struct {
	ID                 int64
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetGeneratorByName(ctx context.Context, name string) (GetGeneratorByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getGeneratorByName, name)
	var i GetGeneratorByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.Effectivity,
		&i.FluidUsagePerTick,
		&i.MaximumTemperature,
		&i.BurnsFluid,
		&i.InputFluid,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateGeneratorByID = `-- name: UpdateGeneratorByID :one
UPDATE generators
SET entity_id = ?1,
energy_source = ?2,
effectivity = ?3,
fluid_usage_per_tick = ?4,
maximum_temperature = ?5,
burns_fluid = ?6,
input_fluid = ?7
WHERE id = ?8
RETURNING id, entity_id, energy_source, effectivity, fluid_usage_per_tick, maximum_temperature, burns_fluid, input_fluid
`

type UpdateGeneratorByIDParams struct {
	EntityID           int64
	EnergySource       []byte
	Effectivity        sql.NullFloat64
	FluidUsagePerTick  sql.NullFloat64
	MaximumTemperature sql.NullFloat64
	BurnsFluid         sql.NullInt64
	InputFluid         sql.NullInt64
	ID                 int64
}

func (q *Queries) UpdateGeneratorByID(ctx context.Context, arg UpdateGeneratorByIDParams) (Generator, error) {
	row := q.db.QueryRowContext(ctx, updateGeneratorByID,
		arg.EntityID,
		arg.EnergySource,
		arg.Effectivity,
		arg.FluidUsagePerTick,
		arg.MaximumTemperature,
		arg.BurnsFluid,
		arg.InputFluid,
		arg.ID,
	)
	var i Generator
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergySource,
		&i.Effectivity,
		&i.FluidUsagePerTick,
		&i.MaximumTemperature,
		&i.BurnsFluid,
		&i.InputFluid,
	)
	return i, err
}
