// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package database

import (
	"context"
	"database/sql"
)

const addItem = `-- name: AddItem :one
INSERT INTO items(
  entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight
`

type AddItemParams struct {
	EntityID    int64
	StackSize   sql.NullInt64
	BurntResult sql.NullInt64
	FuelValue   sql.NullFloat64
	SpoilResult sql.NullInt64
	SpoilTicks  sql.NullInt64
	Weight      sql.NullInt64
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, addItem,
		arg.EntityID,
		arg.StackSize,
		arg.BurntResult,
		arg.FuelValue,
		arg.SpoilResult,
		arg.SpoilTicks,
		arg.Weight,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.StackSize,
		&i.BurntResult,
		&i.FuelValue,
		&i.SpoilResult,
		&i.SpoilTicks,
		&i.Weight,
	)
	return i, err
}

const getAllItemValues = `-- name: GetAllItemValues :many
SELECT id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight FROM items
`

func (q *Queries) GetAllItemValues(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.StackSize,
			&i.BurntResult,
			&i.FuelValue,
			&i.SpoilResult,
			&i.SpoilTicks,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllItems = `-- name: GetAllItems :many

SELECT
items.id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight, entities.id, name, prototype_type, entity_order
FROM items
LEFT JOIN entities
ON items.entity_id = entities.id
`

type GetAllItemsRow struct {
	ID            int64
	EntityID      int64
	StackSize     sql.NullInt64
	BurntResult   sql.NullInt64
	FuelValue     sql.NullFloat64
	SpoilResult   sql.NullInt64
	SpoilTicks    sql.NullInt64
	Weight        sql.NullInt64
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
}

func (q *Queries) GetAllItems(ctx context.Context) ([]GetAllItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsRow
	for rows.Next() {
		var i GetAllItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.StackSize,
			&i.BurntResult,
			&i.FuelValue,
			&i.SpoilResult,
			&i.SpoilTicks,
			&i.Weight,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByEntityID = `-- name: GetItemByEntityID :one
SELECT items.id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight, entities.id, name, prototype_type, entity_order
FROM items
LEFT JOIN entities
ON items.entity_id = entities.id
WHERE entities.id = ?1
`

type GetItemByEntityIDRow struct {
	ID            int64
	EntityID      int64
	StackSize     sql.NullInt64
	BurntResult   sql.NullInt64
	FuelValue     sql.NullFloat64
	SpoilResult   sql.NullInt64
	SpoilTicks    sql.NullInt64
	Weight        sql.NullInt64
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
}

func (q *Queries) GetItemByEntityID(ctx context.Context, id int64) (GetItemByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByEntityID, id)
	var i GetItemByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.StackSize,
		&i.BurntResult,
		&i.FuelValue,
		&i.SpoilResult,
		&i.SpoilTicks,
		&i.Weight,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const getItemByItemID = `-- name: GetItemByItemID :one
SELECT items.id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight, entities.id, name, prototype_type, entity_order
FROM items
LEFT JOIN entities
ON items.entity_id = entities.id
WHERE items.id = ?1
`

type GetItemByItemIDRow struct {
	ID            int64
	EntityID      int64
	StackSize     sql.NullInt64
	BurntResult   sql.NullInt64
	FuelValue     sql.NullFloat64
	SpoilResult   sql.NullInt64
	SpoilTicks    sql.NullInt64
	Weight        sql.NullInt64
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
}

func (q *Queries) GetItemByItemID(ctx context.Context, id int64) (GetItemByItemIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByItemID, id)
	var i GetItemByItemIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.StackSize,
		&i.BurntResult,
		&i.FuelValue,
		&i.SpoilResult,
		&i.SpoilTicks,
		&i.Weight,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const getItemByName = `-- name: GetItemByName :one

SELECT items.id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight, entities.id, name, prototype_type, entity_order
FROM items
LEFT JOIN entities
ON items.entity_id = entities.id
WHERE entities.name = ?1
`

type GetItemByNameRow struct {
	ID            int64
	EntityID      int64
	StackSize     sql.NullInt64
	BurntResult   sql.NullInt64
	FuelValue     sql.NullFloat64
	SpoilResult   sql.NullInt64
	SpoilTicks    sql.NullInt64
	Weight        sql.NullInt64
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
}

func (q *Queries) GetItemByName(ctx context.Context, name string) (GetItemByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByName, name)
	var i GetItemByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.StackSize,
		&i.BurntResult,
		&i.FuelValue,
		&i.SpoilResult,
		&i.SpoilTicks,
		&i.Weight,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
	)
	return i, err
}

const updateItemByID = `-- name: UpdateItemByID :one
UPDATE items
SET entity_id = ?1,
stack_size = ?2,
burnt_result = ?3,
fuel_value = ?4,
spoil_result = ?5,
spoil_ticks = ?6,
weight = ?7
WHERE id = ?8
RETURNING id, entity_id, stack_size, burnt_result, fuel_value, spoil_result, spoil_ticks, weight
`

type UpdateItemByIDParams struct {
	EntityID    int64
	StackSize   sql.NullInt64
	BurntResult sql.NullInt64
	FuelValue   sql.NullFloat64
	SpoilResult sql.NullInt64
	SpoilTicks  sql.NullInt64
	Weight      sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItemByID,
		arg.EntityID,
		arg.StackSize,
		arg.BurntResult,
		arg.FuelValue,
		arg.SpoilResult,
		arg.SpoilTicks,
		arg.Weight,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.StackSize,
		&i.BurntResult,
		&i.FuelValue,
		&i.SpoilResult,
		&i.SpoilTicks,
		&i.Weight,
	)
	return i, err
}
