// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type AssemblyMachine struct {
	ID                 int64
	EntityID           int64
	CraftingCategories []byte
	CraftingSpeed      sql.NullFloat64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	FixedRecipe        sql.NullInt64
}

type Entity struct {
	ID            int64
	Name          string
	PrototypeType string
	EntityOrder   sql.NullString
	LocalisedName string
}

type Fluid struct {
	ID                 int64
	EntityID           int64
	FuelValue          sql.NullFloat64
	GasTemperature     sql.NullInt64
	DefaultTemperature sql.NullInt64
	MaxTemperature     sql.NullInt64
}

type Item struct {
	ID          int64
	EntityID    int64
	StackSize   sql.NullInt64
	BurntResult sql.NullInt64
	FuelValue   sql.NullFloat64
	SpoilResult sql.NullInt64
	SpoilTicks  sql.NullInt64
	Weight      sql.NullInt64
}

type Recipe struct {
	ID             int64
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
}

type Resource struct {
	ID            int64
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
}

type ResourceProducer struct {
	ID                 int64
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
}
