// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package database

import (
	"context"
	"database/sql"
)

const addRecipe = `-- name: AddRecipe :one
INSERT INTO recipes(
  entity_id, energy_required, category, main_product, ingredient, results
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, entity_id, energy_required, category, main_product, ingredient, results
`

type AddRecipeParams struct {
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
}

func (q *Queries) AddRecipe(ctx context.Context, arg AddRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, addRecipe,
		arg.EntityID,
		arg.EnergyRequired,
		arg.Category,
		arg.MainProduct,
		arg.Ingredient,
		arg.Results,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergyRequired,
		&i.Category,
		&i.MainProduct,
		&i.Ingredient,
		&i.Results,
	)
	return i, err
}

const getAllRecipeValues = `-- name: GetAllRecipeValues :many
SELECT id, entity_id, energy_required, category, main_product, ingredient, results FROM recipes
`

func (q *Queries) GetAllRecipeValues(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getAllRecipeValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergyRequired,
			&i.Category,
			&i.MainProduct,
			&i.Ingredient,
			&i.Results,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRecipes = `-- name: GetAllRecipes :many
SELECT recipes.id, entity_id, energy_required, category, main_product, ingredient, results, entities.id, name, prototype_type, entity_order, localised_name
FROM recipes
LEFT JOIN entities
ON recipes.entity_id = entities.id
`

type GetAllRecipesRow struct {
	ID             int64
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
	ID_2           sql.NullInt64
	Name           sql.NullString
	PrototypeType  sql.NullString
	EntityOrder    sql.NullString
	LocalisedName  sql.NullString
}

func (q *Queries) GetAllRecipes(ctx context.Context) ([]GetAllRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRecipesRow
	for rows.Next() {
		var i GetAllRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EnergyRequired,
			&i.Category,
			&i.MainProduct,
			&i.Ingredient,
			&i.Results,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeByEntityID = `-- name: GetRecipeByEntityID :one
SELECT recipes.id, entity_id, energy_required, category, main_product, ingredient, results, entities.id, name, prototype_type, entity_order, localised_name
FROM recipes
LEFT JOIN entities
ON recipes.entity_id = entities.id
WHERE entities.id = ?1
`

type GetRecipeByEntityIDRow struct {
	ID             int64
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
	ID_2           sql.NullInt64
	Name           sql.NullString
	PrototypeType  sql.NullString
	EntityOrder    sql.NullString
	LocalisedName  sql.NullString
}

func (q *Queries) GetRecipeByEntityID(ctx context.Context, id int64) (GetRecipeByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByEntityID, id)
	var i GetRecipeByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergyRequired,
		&i.Category,
		&i.MainProduct,
		&i.Ingredient,
		&i.Results,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getRecipeByName = `-- name: GetRecipeByName :one
SELECT recipes.id, entity_id, energy_required, category, main_product, ingredient, results, entities.id, name, prototype_type, entity_order, localised_name
FROM recipes
LEFT JOIN entities
ON recipes.entity_id = entities.id
WHERE entities.name = ?1
`

type GetRecipeByNameRow struct {
	ID             int64
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
	ID_2           sql.NullInt64
	Name           sql.NullString
	PrototypeType  sql.NullString
	EntityOrder    sql.NullString
	LocalisedName  sql.NullString
}

func (q *Queries) GetRecipeByName(ctx context.Context, name string) (GetRecipeByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByName, name)
	var i GetRecipeByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergyRequired,
		&i.Category,
		&i.MainProduct,
		&i.Ingredient,
		&i.Results,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getRecipeByRecipeID = `-- name: GetRecipeByRecipeID :one
SELECT recipes.id, entity_id, energy_required, category, main_product, ingredient, results, entities.id, name, prototype_type, entity_order, localised_name
FROM recipes
LEFT JOIN entities
ON recipes.entity_id = entities.id
WHERE recipes.id = ?1
`

type GetRecipeByRecipeIDRow struct {
	ID             int64
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
	ID_2           sql.NullInt64
	Name           sql.NullString
	PrototypeType  sql.NullString
	EntityOrder    sql.NullString
	LocalisedName  sql.NullString
}

func (q *Queries) GetRecipeByRecipeID(ctx context.Context, id int64) (GetRecipeByRecipeIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByRecipeID, id)
	var i GetRecipeByRecipeIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergyRequired,
		&i.Category,
		&i.MainProduct,
		&i.Ingredient,
		&i.Results,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateRecipeByID = `-- name: UpdateRecipeByID :one
UPDATE recipes
SET entity_id = ?1,
energy_required = ?2,
category = ?3,
main_product = ?4,
ingredient = ?5,
results = ?6
WHERE id = ?7
RETURNING id, entity_id, energy_required, category, main_product, ingredient, results
`

type UpdateRecipeByIDParams struct {
	EntityID       int64
	EnergyRequired sql.NullFloat64
	Category       sql.NullString
	MainProduct    sql.NullInt64
	Ingredient     []byte
	Results        []byte
	ID             int64
}

func (q *Queries) UpdateRecipeByID(ctx context.Context, arg UpdateRecipeByIDParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeByID,
		arg.EntityID,
		arg.EnergyRequired,
		arg.Category,
		arg.MainProduct,
		arg.Ingredient,
		arg.Results,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EnergyRequired,
		&i.Category,
		&i.MainProduct,
		&i.Ingredient,
		&i.Results,
	)
	return i, err
}
