// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package database

import (
	"context"
	"database/sql"
)

const addResource = `-- name: AddResource :one
INSERT INTO resources(
  entity_id, mining_time, results, required_fluid, category
) VALUES (
  ?1, ?2, ?3, ?4, ?5
) RETURNING id, entity_id, mining_time, results, required_fluid, category
`

type AddResourceParams struct {
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
}

func (q *Queries) AddResource(ctx context.Context, arg AddResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, addResource,
		arg.EntityID,
		arg.MiningTime,
		arg.Results,
		arg.RequiredFluid,
		arg.Category,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MiningTime,
		&i.Results,
		&i.RequiredFluid,
		&i.Category,
	)
	return i, err
}

const getAllResourceValues = `-- name: GetAllResourceValues :many
SELECT id, entity_id, mining_time, results, required_fluid, category FROM resources
`

func (q *Queries) GetAllResourceValues(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getAllResourceValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.MiningTime,
			&i.Results,
			&i.RequiredFluid,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllResources = `-- name: GetAllResources :many
SELECT resources.id, entity_id, mining_time, results, required_fluid, category, entities.id, name, prototype_type, entity_order, localised_name
FROM resources
LEFT JOIN entities
ON resources.entity_id = entities.id
`

type GetAllResourcesRow struct {
	ID            int64
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
	LocalisedName sql.NullString
}

func (q *Queries) GetAllResources(ctx context.Context) ([]GetAllResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllResourcesRow
	for rows.Next() {
		var i GetAllResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.MiningTime,
			&i.Results,
			&i.RequiredFluid,
			&i.Category,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceByEntityID = `-- name: GetResourceByEntityID :one
SELECT resources.id, entity_id, mining_time, results, required_fluid, category, entities.id, name, prototype_type, entity_order, localised_name
FROM resources
LEFT JOIN entities
ON resources.entity_id = entities.id
WHERE entities.id = ?1
`

type GetResourceByEntityIDRow struct {
	ID            int64
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
	LocalisedName sql.NullString
}

func (q *Queries) GetResourceByEntityID(ctx context.Context, id int64) (GetResourceByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceByEntityID, id)
	var i GetResourceByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MiningTime,
		&i.Results,
		&i.RequiredFluid,
		&i.Category,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getResourceByName = `-- name: GetResourceByName :one
SELECT resources.id, entity_id, mining_time, results, required_fluid, category, entities.id, name, prototype_type, entity_order, localised_name
FROM resources
LEFT JOIN entities
ON resources.entity_id = entities.id
WHERE entities.name = ?1
`

type GetResourceByNameRow struct {
	ID            int64
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
	LocalisedName sql.NullString
}

func (q *Queries) GetResourceByName(ctx context.Context, name string) (GetResourceByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceByName, name)
	var i GetResourceByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MiningTime,
		&i.Results,
		&i.RequiredFluid,
		&i.Category,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getResourceByResourceID = `-- name: GetResourceByResourceID :one
SELECT resources.id, entity_id, mining_time, results, required_fluid, category, entities.id, name, prototype_type, entity_order, localised_name
FROM resources
LEFT JOIN entities
ON resources.entity_id = entities.id
WHERE resources.id = ?1
`

type GetResourceByResourceIDRow struct {
	ID            int64
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
	ID_2          sql.NullInt64
	Name          sql.NullString
	PrototypeType sql.NullString
	EntityOrder   sql.NullString
	LocalisedName sql.NullString
}

func (q *Queries) GetResourceByResourceID(ctx context.Context, id int64) (GetResourceByResourceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceByResourceID, id)
	var i GetResourceByResourceIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MiningTime,
		&i.Results,
		&i.RequiredFluid,
		&i.Category,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateResourceByID = `-- name: UpdateResourceByID :one
UPDATE resources
SET entity_id = ?1,
mining_time = ?2,
results = ?3,
required_fluid = ?4,
category = ?5
WHERE id = ?6
RETURNING id, entity_id, mining_time, results, required_fluid, category
`

type UpdateResourceByIDParams struct {
	EntityID      int64
	MiningTime    sql.NullFloat64
	Results       []byte
	RequiredFluid sql.NullInt64
	Category      sql.NullString
	ID            int64
}

func (q *Queries) UpdateResourceByID(ctx context.Context, arg UpdateResourceByIDParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResourceByID,
		arg.EntityID,
		arg.MiningTime,
		arg.Results,
		arg.RequiredFluid,
		arg.Category,
		arg.ID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.MiningTime,
		&i.Results,
		&i.RequiredFluid,
		&i.Category,
	)
	return i, err
}
