// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_producers.sql

package database

import (
	"context"
	"database/sql"
)

const addResourceProducer = `-- name: AddResourceProducer :one
INSERT INTO resource_producers(
  entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7
) RETURNING id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage
`

type AddResourceProducerParams struct {
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
}

func (q *Queries) AddResourceProducer(ctx context.Context, arg AddResourceProducerParams) (ResourceProducer, error) {
	row := q.db.QueryRowContext(ctx, addResourceProducer,
		arg.EntityID,
		arg.ResourceCategories,
		arg.MiningSpeed,
		arg.PumpingSpeed,
		arg.ProducedFluid,
		arg.EnergySource,
		arg.EnergyUsage,
	)
	var i ResourceProducer
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ResourceCategories,
		&i.MiningSpeed,
		&i.PumpingSpeed,
		&i.ProducedFluid,
		&i.EnergySource,
		&i.EnergyUsage,
	)
	return i, err
}

const getAllResourceProducerValues = `-- name: GetAllResourceProducerValues :many
SELECT id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage FROM resource_producers
`

func (q *Queries) GetAllResourceProducerValues(ctx context.Context) ([]ResourceProducer, error) {
	rows, err := q.db.QueryContext(ctx, getAllResourceProducerValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceProducer
	for rows.Next() {
		var i ResourceProducer
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ResourceCategories,
			&i.MiningSpeed,
			&i.PumpingSpeed,
			&i.ProducedFluid,
			&i.EnergySource,
			&i.EnergyUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllResourceProducers = `-- name: GetAllResourceProducers :many
SELECT resource_producers.id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage, entities.id, name, prototype_type, entity_order, localised_name
FROM resource_producers
LEFT JOIN entities
ON resource_producers.entity_id = entities.id
`

type GetAllResourceProducersRow struct {
	ID                 int64
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetAllResourceProducers(ctx context.Context) ([]GetAllResourceProducersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllResourceProducers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllResourceProducersRow
	for rows.Next() {
		var i GetAllResourceProducersRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ResourceCategories,
			&i.MiningSpeed,
			&i.PumpingSpeed,
			&i.ProducedFluid,
			&i.EnergySource,
			&i.EnergyUsage,
			&i.ID_2,
			&i.Name,
			&i.PrototypeType,
			&i.EntityOrder,
			&i.LocalisedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceProducerByEntityID = `-- name: GetResourceProducerByEntityID :one
SELECT resource_producers.id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage, entities.id, name, prototype_type, entity_order, localised_name
FROM resource_producers
LEFT JOIN entities
ON resource_producers.entity_id = entities.id
WHERE entities.id = ?1
`

type GetResourceProducerByEntityIDRow struct {
	ID                 int64
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetResourceProducerByEntityID(ctx context.Context, id int64) (GetResourceProducerByEntityIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceProducerByEntityID, id)
	var i GetResourceProducerByEntityIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ResourceCategories,
		&i.MiningSpeed,
		&i.PumpingSpeed,
		&i.ProducedFluid,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getResourceProducerByName = `-- name: GetResourceProducerByName :one
SELECT resource_producers.id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage, entities.id, name, prototype_type, entity_order, localised_name
FROM resource_producers
LEFT JOIN entities
ON resource_producers.entity_id = entities.id
WHERE entities.name = ?1
`

type GetResourceProducerByNameRow struct {
	ID                 int64
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetResourceProducerByName(ctx context.Context, name string) (GetResourceProducerByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceProducerByName, name)
	var i GetResourceProducerByNameRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ResourceCategories,
		&i.MiningSpeed,
		&i.PumpingSpeed,
		&i.ProducedFluid,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const getResourceProducerByResourceProducerID = `-- name: GetResourceProducerByResourceProducerID :one
SELECT resource_producers.id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage, entities.id, name, prototype_type, entity_order, localised_name
FROM resource_producers
LEFT JOIN entities
ON resource_producers.entity_id = entities.id
WHERE resource_producers.id = ?1
`

type GetResourceProducerByResourceProducerIDRow struct {
	ID                 int64
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	ID_2               sql.NullInt64
	Name               sql.NullString
	PrototypeType      sql.NullString
	EntityOrder        sql.NullString
	LocalisedName      sql.NullString
}

func (q *Queries) GetResourceProducerByResourceProducerID(ctx context.Context, id int64) (GetResourceProducerByResourceProducerIDRow, error) {
	row := q.db.QueryRowContext(ctx, getResourceProducerByResourceProducerID, id)
	var i GetResourceProducerByResourceProducerIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ResourceCategories,
		&i.MiningSpeed,
		&i.PumpingSpeed,
		&i.ProducedFluid,
		&i.EnergySource,
		&i.EnergyUsage,
		&i.ID_2,
		&i.Name,
		&i.PrototypeType,
		&i.EntityOrder,
		&i.LocalisedName,
	)
	return i, err
}

const updateResourceProducerByID = `-- name: UpdateResourceProducerByID :one
UPDATE resource_producers
SET entity_id = ?1,
resource_categories = ?2,
mining_speed = ?3,
pumping_speed = ?4,
produced_fluid = ?5,
energy_source = ?6,
energy_usage = ?7
WHERE id = ?8
RETURNING id, entity_id, resource_categories, mining_speed, pumping_speed, produced_fluid, energy_source, energy_usage
`

type UpdateResourceProducerByIDParams struct {
	EntityID           int64
	ResourceCategories []byte
	MiningSpeed        sql.NullFloat64
	PumpingSpeed       sql.NullFloat64
	ProducedFluid      sql.NullInt64
	EnergySource       []byte
	EnergyUsage        sql.NullFloat64
	ID                 int64
}

func (q *Queries) UpdateResourceProducerByID(ctx context.Context, arg UpdateResourceProducerByIDParams) (ResourceProducer, error) {
	row := q.db.QueryRowContext(ctx, updateResourceProducerByID,
		arg.EntityID,
		arg.ResourceCategories,
		arg.MiningSpeed,
		arg.PumpingSpeed,
		arg.ProducedFluid,
		arg.EnergySource,
		arg.EnergyUsage,
		arg.ID,
	)
	var i ResourceProducer
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.ResourceCategories,
		&i.MiningSpeed,
		&i.PumpingSpeed,
		&i.ProducedFluid,
		&i.EnergySource,
		&i.EnergyUsage,
	)
	return i, err
}
